### ISSUE TITLE
Complete the decision page with the information about the domain model (Impact)

### ISSUE THREAD

**Issue by tzaika** [EVATool/fae-architecture-log#27]
The decision page must contain the information about the domain model of Team - Impact

**Comment by HenningBuhl** [comment]
Das sieht gut aus. Vielleich das reine business model entfernen damit man nur eine Sache hat auch die sich der Lesen konzentriert. Die decision kann erst mal so bleiben. Der Stakeholder meinte ja, es ändert sich bestimmt noch etwas im Verlauf des Projekts
