### ISSUE TITLE
Determine Test Naming Conventions

### ISSUE THREAD

**Issue by HenningBuhl** [EVATool/fae-architecture-log#31]
## Tests conventions
* Class name ends with postfix 'Test'
* Test-Data-Generator-Classes have prefix 'Test'
* Test-Method-Names should look like:
    * testMethod_State_Happens()
    * testMethod_Given_Then()
    * testToString_DefaultObject_DoesNotThrowException()
    * testFindById_ExistingImpact_ReturnImpact()
* Test-Methods have (nearly always) three parts: '// given, // when, // then'
* For Asserts we use AssertJ - fluent assertions java library
    * assertThat( actual ).isEqualTo( expected )
    * assertThat( actualList).hasSize( expectedSize )
    * assertThat( actualList).contains( expectedValue ...)
* For general SetUp in one Test-Class we Use @Before and all other useful JUnit Annotations

**Comment by tzaika** [comment]
needs a review.
